spring.application.name=learning-service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5436/learning_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true