spring.application.name=eureka-server

server.port=8761

# Ce serveur est le registre lui-même.
# Il ne doit pas essayer de s'enregistrer auprès d'un autre Eureka.
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Désactive l'auto-préservation pour le développement.
eureka.server.enable-self-preservation=false